from .bigbench_groups import *
from .blimp_groups import *
from .popularity import *


imppres_presupposition=['presupposition_all_n_presupposition',
 'presupposition_both_presupposition',
 'presupposition_change_of_state',
 'presupposition_cleft_existence',
 'presupposition_cleft_uniqueness',
 'presupposition_only_presupposition',
 'presupposition_possessed_definites_existence',
 'presupposition_possessed_definites_uniqueness',
 'presupposition_question_presupposition']

imppres_implicature=['implicature_connectives',
 'implicature_gradable_adjective',
 'implicature_gradable_verb',
 'implicature_modals',
 'implicature_numerals_10_100',
 'implicature_numerals_2_3',
 'implicature_quantifiers']


crossfit=['emo',
 'wiki_auto',
 'liar',
 'tab_fact',
 'sms_spam',
 'google_wellformed_query',
 'glue',
 'poem_sentiment',
 'emotion',
 'hate_speech18',
 'hatexplain',
 'yahoo_answers_topics',
 'mc_taco',
 'glue',
 'mocha',
 'super_glue',
 'glue',
 'yelp_polarity',
 'tweet_eval',
 'glue',
 'art',
 'super_glue',
 'ethos',
 'app_reviews',
 'yelp_review_full',
 'anli',
 'hate_speech_offensive',
 'climate_fever',
 'circa',
 'financial_phrasebank',
 'wiki_qa',
 'rotten_tomatoes',
 'trec',
 'medical_questions_pairs',
 'glue',
 'super_glue',
 'ade_corpus_v2',
 'sick',
 'super_glue',
 'blimp',
 'discovery',
 'health_fact',
 'ag_news',
 'boolq',
 'glue',
 'amazon_polarity',
 'scicite',
 'dbpedia_14',
 'onestop_english',
 'crows_pairs',
 'scitail',
 'piqa',
 'glue',
 'paws',
 'imdb',
 'glue',
 'trec']


udep_labels = ['nummod:gov', 'acl:attr', 'cop', 'compound:lvc', 'xcomp:ds', 'dep:alt', 'nmod:flat', 'nmod:tmod', 'aux', 'aux:aglt', 'obl:poss', 'acl:poss', 'expl:pass', 'xcomp:cleft', 'aux:part', 'flat:repeat', 'parataxis:discourse', 'advcl:cleft', 'obl:npmod', 'ccomp:cleft', 'dep:prt', 'nmod:cau', 'goeswith', 'parataxis:conj', 'compound:prt', 'compound:vv', 'parataxis:obj', 'nsubj:lvc', 'xcomp:pred', 'expl:pv', 'dislocated:conj', 'compound:plur', 'det:numgov', 'compound:a', 'amod', 'nmod:bahuv', 'nsubj:caus', 'csubj', 'advmod:neg', 'nmod:relat', 'xcomp:obl', 'parataxis:nsubj', 'case:circ', 'advcl:periph', 'nummod:flat', 'det:nummod', 'nmod', 'nmod:own', 'mark:relcl', 'amod:emph', 'parataxis', 'mark:comp', 'advcl:mmod', 'mark', 'acl:relcl', 'dislocated:obj', 'obl:smod', 'det:def', 'xcomp:subj', 'advmod', 'aux:opt', 'advmod:emph', 'advcl:svc', 'nmod:obllvc', 'mark:advb', 'nsubj:own', 'flat:range', 'appos', 'aux:poss', 'compound:affix', 'nummod:mod', 'obl:arg', 'advcl:cmpr', 'obl:inst', 'nmod:ref', 'compound:nv', 'det:poss', 'expl:comp', 'expl:poss', 'nmod:gen', 'advmod:cc', 'advcl:tmod', 'obl:prep', 'parataxis:speech', 'reparandum', 'acl:adv', 'obl:sentcon', 'nmod:abl', 'compound:svc', 'compound:vo', 'obl:soc', 'nmod:comp', 'aux:neg', 'advmod:locy', 'det', 'aux:cnd', 'advcl:coverb', 'acl:appos', 'list', 'compound:quant', 'parataxis:appos', 'nmod:part', 'dislocated:nmod', 'obl:abl', 'flat', 'nmod:pred', 'dep:comp', 'vocative:mention', 'obl:mod', 'cop:locat', 'advmod:arg', 'nmod:dat', 'nsubj:nc', 'xcomp:sp', 'cop:own', 'flat:num', 'obl:cmpr', 'obj:cau', 'flat:name', 'case:pref', 'ccomp:pred', 'expl', 'dislocated:obl', 'mark:adv', 'nummod', 'case:gen', 'cc', 'obl:lmod', 'compound:dir', 'xcomp', 'advcl:arg', 'aux:aspect', 'nummod:periph', 'flat:title', 'case:adv', 'obj:agent', 'cc:preconj', 'advcl:cond', 'parataxis:trans', 'nmod:clas', 'dislocated', 'nmod:gobj', 'nmod:npmod', 'ccomp:obl', 'amod:advmod', 'case:loc', 'nmod:arg', 'nsubj:lfoc', 'discourse:emo', 'obj:caus', 'advmod:mmod', 'det:predet', 'aux:imp', 'discourse:filler', 'iobj:appl', 'iobj', 'nummod:entity', 'nsubj:appos', 'nmod:obl', 'nsubj:bfoc', 'parataxis:parenth', 'obl:own', 'advmod:que', 'nmod:periph', 'dislocated:cleft', 'flat:foreign', 'cop:expl', 'amod:flat', 'nmod:gsubj', 'fixed', 'acl:part', 'advmod:periph', 'iobj:agent', 'expl:impers', 'discourse', 'xcomp:adj', 'det:noun', 'expl:subj', 'parataxis:insert', 'obj:appl', 'cc:nc', 'conj:extend', 'csubj:cleft', 'compound:lv', 'ccomp:pmod', 'det:rel', 'case', 'obl:x', 'parataxis:dislocated', 'parataxis:restart', 'nmod:poss', 'advmod:lmod', 'obj', 'compound:coll', 'iobj:caus', 'dislocated:acl', 'advmod:det', 'compound', 'aux:caus', 'advmod:mode', 'advcl', 'nmod:appos', 'obl:appl', 'advmod:tfrom', 'case:pred', 'nsubj:ifoc', 'root', 'obl:patient', 'advmod:tto', 'advmod:tmod', 'obj:lvc', 'case:det', 'parataxis:deletion', 'obl:pmod', 'advcl:relcl', 'acl:focus', 'advmod:deg', 'compound:conjv', 'compound:redup', 'nmod:agent', 'aux:pass', 'mark:prt', 'nmod:pmod', 'advcl:sp', 'amod:att', 'obl', 'amod:obl', 'ccomp', 'acl', 'case:dec', 'dep:mod', 'discourse:sp', 'obj:advmod', 'nmod:gmod', 'advcl:tcl', 'obl:loc', 'nsubj:periph', 'parataxis:newsent', 'det:adj', 'ccomp:agent', 'nmod:attr', 'conj:svc', 'case:voc', 'conj', 'clf', 'iobj:loc', 'appos:trans', 'dislocated:nsubj', 'det:pron', 'parataxis:rep', 'nmod:advmod', 'dep', 'advmod:df', 'flat:vv', 'ccomp:obj', 'discourse:intj', 'parataxis:rel', 'flat:abs', 'case:acc', 'obl:agent', 'obl:ben', 'nsubj', 'nsubj:cop', 'iobj:patient', 'nmod:cmp', 'compound:smixut', 'flat:sibl', 'mark:rel', 'compound:preverb', 'advcl:lmod', 'vocative', 'orphan', 'obj:periph', 'amod:mode', 'acl:relat', 'csubj:cop', 'advmod:tlocy', 'advmod:to', '_', 'aux:clitic', 'csubj:pass', 'xcomp:obj', 'conj:expl', 'obl:tmod', 'nmod:lmod', 'compound:nn', 'parataxis:hashtag', 'nsubj:pass', 'acl:periph', 'obl:advmod', 'aux:mood', 'nmod:att', 'aux:q', 'nsubj:obj', 'acl:inf', 'punct', 'acl:cleft', 'nummod:det', 'aux:tense', 'compound:ext']