from .bigbench_groups import *
from .blimp_groups import *
from .popularity import *


imppres_presupposition=['presupposition_all_n_presupposition',
 'presupposition_both_presupposition',
 'presupposition_change_of_state',
 'presupposition_cleft_existence',
 'presupposition_cleft_uniqueness',
 'presupposition_only_presupposition',
 'presupposition_possessed_definites_existence',
 'presupposition_possessed_definites_uniqueness',
 'presupposition_question_presupposition']

imppres_implicature=['implicature_connectives',
 'implicature_gradable_adjective',
 'implicature_gradable_verb',
 'implicature_modals',
 'implicature_numerals_10_100',
 'implicature_numerals_2_3',
 'implicature_quantifiers']


crossfit=['emo',
 'wiki_auto',
 'liar',
 'tab_fact',
 'sms_spam',
 'google_wellformed_query',
 'glue',
 'poem_sentiment',
 'emotion',
 'hate_speech18',
 'hatexplain',
 'yahoo_answers_topics',
 'mc_taco',
 'glue',
 'mocha',
 'super_glue',
 'glue',
 'yelp_polarity',
 'tweet_eval',
 'glue',
 'art',
 'super_glue',
 'ethos',
 'app_reviews',
 'yelp_review_full',
 'anli',
 'hate_speech_offensive',
 'climate_fever',
 'circa',
 'financial_phrasebank',
 'wiki_qa',
 'rotten_tomatoes',
 'trec',
 'medical_questions_pairs',
 'glue',
 'super_glue',
 'ade_corpus_v2',
 'sick',
 'super_glue',
 'blimp',
 'discovery',
 'health_fact',
 'ag_news',
 'boolq',
 'glue',
 'amazon_polarity',
 'scicite',
 'dbpedia_14',
 'onestop_english',
 'crows_pairs',
 'scitail',
 'piqa',
 'glue',
 'paws',
 'imdb',
 'glue',
 'trec']