"""Hub dataset card licenses (generated by scripts/update_licenses.py).

Repo -> the card's ``license`` list, ``unknown`` dropped; empty when the card has none."""

CARD_LICENSES = {
 "12ml/e-CARE": [],
 "AmazonScience/massive": [
  "cc-by-4.0"
 ],
 "AndyChiang/cloth": [
  "mit"
 ],
 "AndyChiang/dgen": [
  "mit"
 ],
 "Anthropic/persuasion": [
  "cc-by-nc-sa-4.0"
 ],
 "AshtonIsNotHere/biosift-nli": [],
 "AshtonIsNotHere/nli4ct_semeval2024": [],
 "Brand24/mms": [
  "other"
 ],
 "CLUTRR/v1": [],
 "CogComp/mc_taco": [],
 "CogComp/trec": [],
 "ColumbiaNLP/FLUTE": [
  "afl-3.0"
 ],
 "DFKI-SLT/few-nerd": [
  "cc-by-sa-4.0"
 ],
 "Dahoas/synthetic-instruct-gptj-pairwise": [],
 "Deehan1866/processed_phrase_similarity": [],
 "Dzeniks/hover": [
  "mit"
 ],
 "Dzeniks/hover-3way": [
  "mit"
 ],
 "EleutherAI/headqa": [
  "other"
 ],
 "GBaker/MedQA-USMLE-4-options-hf": [
  "cc-by-sa-4.0"
 ],
 "GGLab/PARADISE": [
  "mit"
 ],
 "HannahRoseKirk/HatemojiBuild": [
  "cc-by-4.0"
 ],
 "Hate-speech-CNERG/hatexplain": [
  "cc-by-4.0"
 ],
 "INK-USC/numer_sense": [
  "mit"
 ],
 "INK-USC/riddle_sense": [
  "other"
 ],
 "INK-USC/xcsr": [
  "mit"
 ],
 "IlyaGusev/headline_cause": [
  "cc0-1.0"
 ],
 "ImperialCollegeLondon/health_fact": [
  "mit"
 ],
 "Jiangjie/ekar_english": [
  "afl-3.0"
 ],
 "Korea-MES/open_question_type": [],
 "LabHC/moral_stories": [],
 "MartinThoma/wili_2018": [
  "odbl"
 ],
 "MoE-UNC/wikihop": [],
 "MoritzLaurer/dataset_train_nli": [],
 "MoritzLaurer/multilingual-NLI-26lang-2mil7": [],
 "MultiCoNER/multiconer_v2": [
  "cc-by-4.0"
 ],
 "PKU-Alignment/BeaverTails": [
  "cc-by-nc-4.0"
 ],
 "PKU-Alignment/PKU-SafeRLHF": [
  "cc-by-nc-4.0"
 ],
 "PhilipMay/stsb_multi_mt": [
  "other"
 ],
 "PiC/phrase_similarity": [
  "cc-by-nc-4.0"
 ],
 "PierreColombo/miam": [
  "cc-by-sa-4.0"
 ],
 "PolyAI/banking77": [
  "cc-by-4.0"
 ],
 "QAngaroo/wiki_hop": [
  "cc-by-sa-3.0"
 ],
 "RobZamp/sick": [
  "cc-by-nc-sa-3.0"
 ],
 "Rowan/hellaswag": [],
 "RuyuanWan/Dilemmas_Disagreement": [],
 "RuyuanWan/Dynasent_Disagreement": [],
 "RuyuanWan/Politeness_Disagreement": [],
 "RuyuanWan/SBIC_Disagreement": [],
 "RuyuanWan/SChem_Disagreement": [],
 "S-Labs/prompt-injection-dataset": [
  "mit"
 ],
 "Salesforce/cos_e": [],
 "Samsoup/cosmos_qa": [],
 "SemEvalWorkshop/emo": [],
 "SemEvalWorkshop/humicroedit": [],
 "SemEvalWorkshop/sem_eval_2010_task_8": [],
 "SetFit/ethos_binary": [],
 "SetFit/insincere-questions": [],
 "SetFit/toxic_conversations": [],
 "SetFit/xglue_nc": [],
 "SpeedOfMagic/ontonotes_english": [],
 "WhereIsAI/github-issue-similarity": [
  "mit"
 ],
 "Yelp/yelp_review_full": [
  "other"
 ],
 "YufeiHFUT/DocRED_origin": [],
 "Zhengping/UNLI": [
  "mit"
 ],
 "ade-benchmark-corpus/ade_corpus_v2": [],
 "ai4bharat/indic_glue": [
  "other"
 ],
 "alisawuffles/WANLI": [
  "cc-by-4.0"
 ],
 "allenai/ai2_arc": [
  "cc-by-sa-4.0"
 ],
 "allenai/art": [],
 "allenai/cosmos_qa": [
  "cc-by-4.0"
 ],
 "allenai/math_qa": [
  "apache-2.0"
 ],
 "allenai/openbookqa": [],
 "allenai/qasc": [
  "cc-by-4.0"
 ],
 "allenai/quartz": [
  "cc-by-4.0"
 ],
 "allenai/scicite": [],
 "allenai/scifact_entailment": [
  "cc-by-nc-2.0"
 ],
 "allenai/sciq": [
  "cc-by-nc-3.0"
 ],
 "allenai/scitail": [],
 "allenai/social_i_qa": [],
 "allenai/swag": [],
 "allenai/wildguardmix": [
  "odc-by"
 ],
 "allenai/winogrande": [],
 "allenai/wiqa": [],
 "amirveyseh/acronym_identification": [
  "mit"
 ],
 "amydeng2000/CREAK": [],
 "aps/dynahate": [],
 "aps/super_glue": [
  "other"
 ],
 "baber/piqa": [],
 "barilan/blog_authorship_corpus": [],
 "bigbio/chemprot": [
  "other"
 ],
 "bogdanminko/wildguardmix-cleaned": [],
 "cambridgeltl/xcopa": [
  "cc-by-4.0"
 ],
 "cardiffnlp/tweet_eval": [],
 "cardiffnlp/tweet_sentiment_multilingual": [],
 "causal-nlp/corr2cause": [],
 "clinc/clinc_oos": [
  "cc-by-3.0"
 ],
 "clue/clue": [],
 "coastalcph/lex_glue": [
  "cc-by-4.0"
 ],
 "community-datasets/definite_pronoun_resolution": [],
 "community-datasets/offenseval_dravidian": [
  "cc-by-4.0"
 ],
 "community-datasets/proto_qa": [
  "cc-by-4.0"
 ],
 "community-datasets/quarel": [],
 "community-datasets/yahoo_answers_topics": [],
 "copenlu/scientific-exaggeration-detection": [
  "gpl-3.0"
 ],
 "cornell-movie-review-data/rotten_tomatoes": [],
 "corypaik/prost": [
  "apache-2.0"
 ],
 "curaihealth/medical_questions_pairs": [],
 "dair-ai/emotion": [
  "other"
 ],
 "dataset-org/dream": [],
 "declare-lab/cicero": [
  "mit"
 ],
 "deepset/prompt-injections": [
  "apache-2.0"
 ],
 "defunct-datasets/amazon_reviews_multi": [
  "other"
 ],
 "demelin/moral_stories": [
  "mit"
 ],
 "demo-org/auditor_review": [],
 "dravidianlangtech/hope_edi": [
  "cc-by-4.0"
 ],
 "dvilares/head_qa": [
  "mit"
 ],
 "dynabench/dynasent": [],
 "ehovy/race": [
  "other"
 ],
 "erbacher/AmbigNQ-clarifying-question": [],
 "eriktks/conll2000": [],
 "eriktks/conll2002": [],
 "eriktks/conll2003": [
  "other"
 ],
 "eusip/silicone": [
  "cc-by-sa-4.0"
 ],
 "facebook/anli": [
  "cc-by-nc-4.0"
 ],
 "facebook/xnli": [],
 "fancyzhx/ag_news": [],
 "fancyzhx/amazon_polarity": [
  "apache-2.0"
 ],
 "fancyzhx/dbpedia_14": [
  "cc-by-sa-3.0"
 ],
 "fireworks-ai/logiqa": [],
 "flaitenberger/wnut_17": [],
 "gabrielloiseau/privacy-200k-Mistral-Large-3": [],
 "ghbacct/financial-phrasebank-all-agree-classification": [],
 "google-research-datasets/circa": [
  "cc-by-4.0"
 ],
 "google-research-datasets/go_emotions": [
  "apache-2.0"
 ],
 "google-research-datasets/google_wellformed_query": [
  "cc-by-sa-4.0"
 ],
 "google-research-datasets/paws": [
  "other"
 ],
 "google-research-datasets/paws-x": [
  "other"
 ],
 "google-research-datasets/poem_sentiment": [
  "cc-by-4.0"
 ],
 "google/civil_comments": [
  "cc0-1.0"
 ],
 "google/code_x_glue_cc_defect_detection": [
  "c-uda"
 ],
 "goosmanlei/amazon_reviews_multi": [
  "other"
 ],
 "heegyu/webgpt_comparisons_ko": [],
 "hendrycks/ethics": [
  "mit"
 ],
 "hendzh/PromptShield": [
  "apache-2.0"
 ],
 "hitachi-nlp/FLD.v2": [],
 "iamollas/ethos": [
  "agpl-3.0"
 ],
 "indonlp/NusaX-senti": [
  "cc-by-sa-4.0"
 ],
 "jana4/turingbench-humanized": [],
 "jaredfern/codah": [
  "odc-by"
 ],
 "jeggers/riddle_sense": [],
 "jhu-cogsci/hans": [],
 "jnlpba/jnlpba": [],
 "joelito/mapa": [
  "cc-by-4.0"
 ],
 "joey234/nan-nli": [
  "cc-by-sa-4.0"
 ],
 "juletxara/xstory_cloze": [
  "cc-by-sa-4.0"
 ],
 "karanxa/agent-action-safety-dataset": [
  "apache-2.0"
 ],
 "khalidalt/offenseval_2020_ar": [],
 "kiddothe2b/contract-nli": [
  "cc-by-nc-sa-4.0"
 ],
 "klue/klue": [
  "cc-by-sa-4.0"
 ],
 "kontext-security/ShellRisk-Bench": [
  "other"
 ],
 "lasha-nlp/CONDAQA": [
  "apache-2.0"
 ],
 "launch/open_question_type": [
  "cc-by-4.0"
 ],
 "legacy-datasets/banking77": [
  "cc-by-4.0"
 ],
 "leondz/wnut_17": [
  "cc-by-4.0"
 ],
 "lighteval/lsat_qa": [],
 "lmsys/chatbot_arena_conversations": [
  "cc"
 ],
 "lmsys/toxic-chat": [
  "cc-by-nc-4.0"
 ],
 "lucasmccabe/logiqa": [],
 "malmaud/onestop_qa": [
  "cc-by-sa-4.0"
 ],
 "marcov/health_fact_promptsource": [],
 "marcov/mc_taco_promptsource": [],
 "masakhane/masakhanews": [
  "afl-3.0"
 ],
 "mhardalov/exams": [
  "cc-by-sa-4.0"
 ],
 "michiel/xstance": [],
 "microsoft/wiki_qa": [
  "other"
 ],
 "microsoft/xglue": [
  "other"
 ],
 "mlburnham/Pol_NLI": [],
 "mteb/AfriSentiClassification": [
  "cc-by-4.0"
 ],
 "mteb/MassiveIntentClassification": [],
 "mteb/NusaX-senti": [
  "cc-by-sa-4.0"
 ],
 "mteb/amazon_counterfactual": [
  "cc-by-4.0"
 ],
 "mteb/tweet_sentiment_multilingual": [
  "cc-by-3.0"
 ],
 "multilingual-discourse-hub/disrpt": [
  "apache-2.0"
 ],
 "mwong/fever-evidence-related": [
  "cc-by-sa-3.0",
  "gpl-3.0"
 ],
 "nala-cub/americas_nli": [
  "cc-by-sa-4.0"
 ],
 "ncbi/ncbi_disease": [],
 "nedjmaou/MLMA_hate_speech": [
  "mit"
 ],
 "neurae/dnd_style_intents": [
  "apache-2.0"
 ],
 "neuralchemy/Prompt-injection-dataset": [
  "apache-2.0"
 ],
 "nightingal3/fig-qa": [
  "mit"
 ],
 "nikhilweee/sharc_modified": [],
 "nlpaueb/finer-139": [
  "cc-by-sa-4.0"
 ],
 "nvidia/HelpSteer": [
  "cc-by-4.0"
 ],
 "nvidia/HelpSteer2": [
  "cc-by-4.0"
 ],
 "nvidia/HelpSteer3": [
  "cc-by-4.0"
 ],
 "nyu-mll/glue": [
  "other"
 ],
 "odegiber/hate_speech18": [
  "cc-by-sa-3.0"
 ],
 "oneonlee/cleansed_emocontext": [
  "mpl-2.0"
 ],
 "openai/summarize_from_feedback": [],
 "openlifescienceai/medmcqa": [
  "apache-2.0"
 ],
 "pacovaldez/stackoverflow-questions": [
  "apache-2.0"
 ],
 "papluca/language-identification": [],
 "pasinit/xlwic": [
  "cc-by-nc-4.0"
 ],
 "philippelaban/hlgd": [
  "apache-2.0"
 ],
 "pietrolesci/add_one_rte": [],
 "pietrolesci/breaking_nli": [],
 "pietrolesci/conj_nli": [],
 "pietrolesci/dialogue_nli": [],
 "pietrolesci/dnc": [],
 "pietrolesci/fracas": [],
 "pietrolesci/gen_debiased_nli": [],
 "pietrolesci/joci": [],
 "pietrolesci/mpe": [],
 "pietrolesci/nli_fever": [],
 "pietrolesci/recast_white": [],
 "pietrolesci/robust_nli": [],
 "pietrolesci/robust_nli_is_sd": [],
 "pietrolesci/robust_nli_li_ts": [],
 "pkavumba/balanced-copa": [
  "cc-by-4.0"
 ],
 "prajjwal1/discosense": [],
 "pushpdeep/UltraFeedback-paired": [
  "mit"
 ],
 "qbao775/PARARULE-Plus": [
  "mit"
 ],
 "raquiba/Sarcasm_News_Headline": [],
 "relbert/lexical_relation_classification": [
  "other"
 ],
 "sadat2307/MSciNLI": [
  "cc-by-sa-4.0"
 ],
 "sealuzh/app_reviews": [],
 "shmuhammad/AfriSenti-twitter-sentiment": [],
 "sihaochen/propsegment": [
  "cc-by-4.0"
 ],
 "sileod/discovery": [
  "apache-2.0"
 ],
 "sileod/mindgames": [
  "apache-2.0"
 ],
 "sileod/missing-item-prediction": [],
 "sileod/pragmeval": [],
 "sileod/probability_words_nli": [],
 "sileod/wikimedqa": [
  "apache-2.0"
 ],
 "skg/toxigen-data": [],
 "sonos-nlu-benchmark/snips_built_in_intents": [
  "cc0-1.0"
 ],
 "stanfordnlp/SHP": [],
 "stanfordnlp/imdb": [
  "other"
 ],
 "stanfordnlp/snli": [
  "cc-by-sa-4.0"
 ],
 "strombergnlp/rumoureval_2019": [
  "cc-by-4.0"
 ],
 "strombergnlp/x-stance": [
  "mit"
 ],
 "takala/financial_phrasebank": [
  "cc-by-nc-sa-3.0"
 ],
 "tals/vitaminc": [
  "cc-by-sa-3.0"
 ],
 "tasksource/AES2-essay-scoring": [
  "cc-by-nc-4.0"
 ],
 "tasksource/AdjectiveScaleProbe-nli": [],
 "tasksource/ConTRoL-nli": [],
 "tasksource/I2D2": [
  "apache-2.0"
 ],
 "tasksource/LogicNLI": [],
 "tasksource/MOH": [],
 "tasksource/PRM800K": [
  "mit"
 ],
 "tasksource/ReSQ": [],
 "tasksource/SDOH-NLI": [
  "cc-by-4.0"
 ],
 "tasksource/SIGA-nli": [],
 "tasksource/ScienceQA_text_only": [],
 "tasksource/SpaRTUN": [],
 "tasksource/SpaceNLI": [
  "mit"
 ],
 "tasksource/TroFi": [
  "gpl"
 ],
 "tasksource/VUAC": [],
 "tasksource/acceptability-prediction": [
  "apache-2.0"
 ],
 "tasksource/ambient": [],
 "tasksource/apt": [],
 "tasksource/arct": [
  "apache-2.0"
 ],
 "tasksource/argument-feedback": [],
 "tasksource/autotnli": [
  "apache-2.0"
 ],
 "tasksource/avicenna": [
  "cc"
 ],
 "tasksource/babi_nli": [
  "bsd"
 ],
 "tasksource/blog_authorship_corpus": [
  "apache-2.0"
 ],
 "tasksource/boolq-natural-perturbations": [],
 "tasksource/brainteasers": [],
 "tasksource/chaos-mnli-ambiguity": [],
 "tasksource/cladder": [
  "mit"
 ],
 "tasksource/clcd-english": [
  "apache-2.0"
 ],
 "tasksource/clutrr": [],
 "tasksource/cnli": [],
 "tasksource/com2sense": [],
 "tasksource/commonsense_qa_2.0": [
  "cc-by-4.0"
 ],
 "tasksource/conceptrules_v2": [
  "mit"
 ],
 "tasksource/contract-nli": [],
 "tasksource/corr2cause": [
  "mit"
 ],
 "tasksource/counterfactually-augmented-imdb": [],
 "tasksource/counterfactually-augmented-snli": [],
 "tasksource/crowdflower": [],
 "tasksource/cycic_classification": [
  "apache-2.0"
 ],
 "tasksource/cycic_multiplechoice": [
  "apache-2.0"
 ],
 "tasksource/dadc-limit-nli": [
  "cc"
 ],
 "tasksource/defeasible-nli": [
  "apache-2.0"
 ],
 "tasksource/doc-nli": [
  "bsd"
 ],
 "tasksource/dynahate": [
  "gpl"
 ],
 "tasksource/dynasent": [],
 "tasksource/english-grading": [],
 "tasksource/equate": [
  "apache-2.0"
 ],
 "tasksource/esci": [
  "apache-2.0"
 ],
 "tasksource/ethos": [],
 "tasksource/feasibilityQA": [
  "mit"
 ],
 "tasksource/few_rel": [],
 "tasksource/folio": [
  "cc"
 ],
 "tasksource/fool-me-twice": [
  "apache-2.0"
 ],
 "tasksource/goal-step-wikihow": [
  "mit"
 ],
 "tasksource/google_wellformed_query": [],
 "tasksource/hans": [],
 "tasksource/hate_speech18": [],
 "tasksource/help-nli": [
  "cc"
 ],
 "tasksource/hh-rlhf": [],
 "tasksource/hlgd": [],
 "tasksource/humicroedit": [],
 "tasksource/icl-symbol-tuning-instruct": [
  "apache-2.0"
 ],
 "tasksource/idioms-nli": [],
 "tasksource/implicatures": [
  "gpl"
 ],
 "tasksource/implicit-hate-stg1": [],
 "tasksource/it-support-tickets": [
  "cc-by-4.0"
 ],
 "tasksource/jigsaw_toxicity": [
  "apache-2.0"
 ],
 "tasksource/lewidi": [
  "other"
 ],
 "tasksource/liar": [],
 "tasksource/lifecycle-entailment": [],
 "tasksource/lingnli": [],
 "tasksource/linguisticprobing": [],
 "tasksource/logical-entailment": [
  "apache-2.0"
 ],
 "tasksource/logical-fallacy": [],
 "tasksource/logiqa-2.0-nli": [
  "cc"
 ],
 "tasksource/lonli": [
  "mit"
 ],
 "tasksource/lsat-ar": [],
 "tasksource/lsat-rc": [],
 "tasksource/math_qa": [],
 "tasksource/mctest-nli": [],
 "tasksource/measuring-hate-speech-votes": [
  "cc-by-4.0"
 ],
 "tasksource/mms": [
  "other"
 ],
 "tasksource/monli": [],
 "tasksource/monotonicity-entailment": [
  "apache-2.0"
 ],
 "tasksource/mtop": [
  "cc-by-sa-4.0"
 ],
 "tasksource/multilingual-sentiments": [],
 "tasksource/multilingual-zero-shot-label-nli": [
  "other"
 ],
 "tasksource/mutual": [],
 "tasksource/natural-language-satisfiability": [],
 "tasksource/naturallogic": [
  "apache-2.0"
 ],
 "tasksource/nlgraph": [],
 "tasksource/nli-veridicality-transitivity": [
  "cc"
 ],
 "tasksource/nope": [],
 "tasksource/numer_sense": [],
 "tasksource/oasst1_dense_flat": [
  "apache-2.0"
 ],
 "tasksource/oasst1_pairwise_rlhf_reward": [],
 "tasksource/oasst2_dense_flat": [],
 "tasksource/oasst2_pairwise_rlhf_reward": [],
 "tasksource/offenseval_2020": [],
 "tasksource/parade": [],
 "tasksource/patent-phrase-similarity": [
  "cc-by-4.0"
 ],
 "tasksource/path-naturalness-prediction": [],
 "tasksource/prm800k_dpo": [
  "mit"
 ],
 "tasksource/procedural-typed-decisions": [
  "apache-2.0"
 ],
 "tasksource/proofwriter": [],
 "tasksource/puzzte": [
  "apache-2.0"
 ],
 "tasksource/race-c": [],
 "tasksource/recast": [],
 "tasksource/reclor": [
  "other"
 ],
 "tasksource/regset": [],
 "tasksource/resnli": [
  "cc-by-4.0"
 ],
 "tasksource/robustLR": [],
 "tasksource/ruletaker": [
  "apache-2.0"
 ],
 "tasksource/scicite": [],
 "tasksource/scifact_entailment": [],
 "tasksource/scinli": [
  "apache-2.0"
 ],
 "tasksource/scone": [
  "cc0-1.0"
 ],
 "tasksource/scruples": [
  "apache-2.0"
 ],
 "tasksource/seahorse_summarization_evaluation": [
  "cc"
 ],
 "tasksource/semantic_fragments_nli": [],
 "tasksource/sen-making": [],
 "tasksource/sharc": [],
 "tasksource/sherliic": [],
 "tasksource/sick": [],
 "tasksource/silicone": [],
 "tasksource/simple_pair": [],
 "tasksource/social_i_qa": [],
 "tasksource/spartqa-mchoice": [
  "mit"
 ],
 "tasksource/spartqa-yn": [
  "apache-2.0"
 ],
 "tasksource/starcon": [],
 "tasksource/stepgame": [
  "mit"
 ],
 "tasksource/strategy-qa": [],
 "tasksource/sts-companion": [
  "apache-2.0"
 ],
 "tasksource/subjectivity": [
  "mit"
 ],
 "tasksource/syntactic-augmentation-nli": [
  "mit"
 ],
 "tasksource/synthetic-retrieval-NLI": [],
 "tasksource/tasksource_dpo_pairs": [],
 "tasksource/temporal-nli": [
  "apache-2.0"
 ],
 "tasksource/tomi-nli": [
  "gpl-3.0"
 ],
 "tasksource/tracie": [
  "apache-2.0"
 ],
 "tasksource/trec": [],
 "tasksource/twentyquestions": [],
 "tasksource/tydi-as2-balanced": [],
 "tasksource/universal-joy": [
  "gpl"
 ],
 "tasksource/wice": [
  "cc-by-sa-4.0"
 ],
 "tasksource/winodict": [
  "cc-by-4.0"
 ],
 "tasksource/winowhy": [
  "mit"
 ],
 "tasksource/wiqa": [],
 "tasksource/wouldyourather": [],
 "tasksource/x-fact": [],
 "tasksource/xglue": [],
 "tasksource/xlwic": [],
 "tasksource/zero-shot-label-nli": [
  "other"
 ],
 "tau/commonsense_qa": [
  "mit"
 ],
 "tdavidson/hate_speech_offensive": [],
 "textmachinelab/quail": [
  "cc-by-nc-sa-4.0"
 ],
 "thunlp/docred": [
  "mit"
 ],
 "tomaarsen/conll2003": [
  "other"
 ],
 "tomngdev/shell-safety-v2": [
  "mit"
 ],
 "turingbench/TuringBench": [
  "apache-2.0"
 ],
 "tweets-hate-speech-detection/tweets_hate_speech_detection": [
  "gpl-3.0"
 ],
 "tyqiangz/multilingual-sentiments": [
  "apache-2.0"
 ],
 "ucberkeley-dlab/measuring-hate-speech": [
  "cc-by-4.0"
 ],
 "ucirvine/sms_spam": [],
 "ucsbai/liar": [],
 "unigram/FOL-nli": [
  "apache-2.0"
 ],
 "universal-dependencies/universal_dependencies": [
  "other"
 ],
 "vwxyzjn/summarize_from_feedback_oai_preprocessing": [],
 "webis/Touche23-ValueEval": [
  "cc-by-4.0"
 ],
 "webis/args_me": [
  "cc-by-4.0"
 ],
 "xTRam1/safe-guard-prompt-injection": [],
 "ybisk/piqa": [],
 "yuweiyin/IntentGrasp": [
  "cc-by-nc-sa-4.0"
 ],
 "zapsdcn/citation_intent": [],
 "zapsdcn/hyperpartisan_news": [],
 "zapsdcn/sciie": [],
 "zeroshot/twitter-financial-news-sentiment": [
  "mit"
 ]
}
