"""Data Provenance Initiative license annotations (generated by scripts/update_dpi_licenses.py).

https://github.com/Data-Provenance-Initiative/Data-Provenance-Collection at ce6662deccf011574427b6f112df479d261960b8.
TASK_LICENSES: tasksource task id -> licenses; REPO_LICENSES: lowercase Hub dataset -> licenses;
LICENSE_USE: license -> DPI use class ("All": commercial, "NC", "Acad", "Unspecified").
"""

DPI_COMMIT = "ce6662deccf011574427b6f112df479d261960b8"

TASK_LICENSES = {
 "CONDAQA": [
  "Apache License 2.0"
 ],
 "ConTRoL-nli": [
  "CC BY-NC-SA 4.0"
 ],
 "NeQA": [
  "CC BY 4.0"
 ],
 "SHP": [
  "Custom"
 ],
 "Touche23-ValueEval": [
  "CC BY 4.0"
 ],
 "TroFi": [
  "Custom"
 ],
 "TuringBench": [
  "Apache License 2.0"
 ],
 "acronym_identification": [
  "CC BY-NC-SA 4.0"
 ],
 "add_one_rte": [
  "Non Commercial"
 ],
 "args_me": [
  "CC BY 4.0"
 ],
 "balanced-copa": [
  "BSD 2-Clause License"
 ],
 "banking77": [
  "CC BY 4.0"
 ],
 "blog_authorship_corpus/gender": [
  "Custom"
 ],
 "blog_authorship_corpus/horoscope": [
  "Custom"
 ],
 "blog_authorship_corpus/job": [
  "Custom"
 ],
 "breaking_nli": [
  "CC BY-SA 4.0"
 ],
 "conceptrules_v2": [
  "Custom"
 ],
 "conll2003/chunk_tags": [
  "Academic Research Purposes Only",
  "Request Form"
 ],
 "conll2003/ner_tags": [
  "Academic Research Purposes Only",
  "Request Form"
 ],
 "conll2003/pos_tags": [
  "Academic Research Purposes Only",
  "Request Form"
 ],
 "defeasible-nli/atomic": [
  "MIT License"
 ],
 "defeasible-nli/snli": [
  "MIT License"
 ],
 "dnc": [
  "Various"
 ],
 "dynasent/dynabench.dynasent.r1.all/r1": [
  "CC BY 4.0"
 ],
 "dynasent/dynabench.dynasent.r2.all/r2": [
  "CC BY 4.0"
 ],
 "e-CARE": [
  "BSD 2-Clause License"
 ],
 "ekar_english": [
  "CC BY-NC-SA 4.0"
 ],
 "fever-evidence-related/mwong--fever-related": [
  "CC BY-SA 4.0"
 ],
 "few-nerd/supervised": [
  "CC BY-SA 4.0"
 ],
 "folio": [
  "CC BY-SA 4.0"
 ],
 "gen_debiased_nli/mnli_par_z": [
  "OANC"
 ],
 "gen_debiased_nli/mnli_seq_z": [
  "OANC"
 ],
 "gen_debiased_nli/mnli_z_aug": [
  "OANC"
 ],
 "gen_debiased_nli/snli_par_z": [
  "CC BY-SA 4.0"
 ],
 "gen_debiased_nli/snli_seq_z": [
  "CC BY-SA 4.0"
 ],
 "gen_debiased_nli/snli_z_aug": [
  "CC BY-SA 4.0"
 ],
 "hate_speech18": [
  "CC BY-SA 3.0"
 ],
 "help-nli": [
  "CC BY-SA 4.0"
 ],
 "hh-rlhf": [
  "MIT License"
 ],
 "hlgd": [
  "Apache License 2.0"
 ],
 "hyperpartisan_news": [
  "CC BY 4.0"
 ],
 "implicit-hate-stg1": [
  "Request Form"
 ],
 "imppres/implicature_connectives/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_connectives/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_gradable_adjective/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_gradable_adjective/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_gradable_verb/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_gradable_verb/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_modals/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_modals/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_numerals_10_100/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_numerals_10_100/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_numerals_2_3/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_numerals_2_3/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_quantifiers/log": [
  "CC BY-NC 4.0"
 ],
 "imppres/implicature_quantifiers/prag": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_all_n_presupposition/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_both_presupposition/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_change_of_state/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_cleft_existence/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_cleft_uniqueness/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_only_presupposition/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_possessed_definites_existence/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_possessed_definites_uniqueness/presupposition": [
  "CC BY-NC 4.0"
 ],
 "imppres/presupposition_question_presupposition/presupposition": [
  "CC BY-NC 4.0"
 ],
 "language-identification": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0",
  "Custom"
 ],
 "lex_glue/scotus": [
  "Custom"
 ],
 "lexical_relation_classification/BLESS": [
  "CC BY-NC 4.0"
 ],
 "lexical_relation_classification/CogALexV": [
  "CC BY-NC 4.0"
 ],
 "lexical_relation_classification/EVALution": [
  "CC BY-NC 4.0"
 ],
 "lexical_relation_classification/K&H+N": [
  "CC BY-NC 4.0"
 ],
 "lexical_relation_classification/ROOT09": [
  "CC BY-NC 4.0"
 ],
 "logiqa-2.0-nli": [
  "CC BY-NC-SA 4.0"
 ],
 "mbib-base/cognitive-bias": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/fake-news": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/gender-bias": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/hate-speech": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/linguistic-bias": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/political-bias": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/racial-bias": [
  "CC BY-SA 4.0"
 ],
 "mbib-base/text-level-bias": [
  "CC BY-SA 4.0"
 ],
 "mindgames": [
  "Apache License 2.0"
 ],
 "model-written-evals": [
  "CC BY 4.0"
 ],
 "onestop_qa": [
  "CC BY-SA 4.0"
 ],
 "ontonotes_english/SpeedOfMagic--ontonotes_english": [
  "No License"
 ],
 "phrase_similarity": [
  "CC BY-NC 4.0"
 ],
 "probability_words_nli/reasoning_1hop": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "probability_words_nli/reasoning_2hop": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "probability_words_nli/usnli": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "prost": [
  "Apache License 2.0"
 ],
 "quote-repetition": [
  "CC BY 4.0"
 ],
 "race-c": [
  "Non Commercial"
 ],
 "recast/recast_factuality": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_megaveridicality": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_ner": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_puns": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_sentiment": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_verbcorner": [
  "CC BY-SA 4.0"
 ],
 "recast/recast_verbnet": [
  "CC BY-SA 4.0"
 ],
 "redefine-math": [
  "CC BY 4.0"
 ],
 "riddle_sense": [
  "Request Form"
 ],
 "robust_nli/IS_CS": [
  "CC BY-SA 4.0",
  "MIT License",
  "OANC"
 ],
 "robust_nli/LI_LI": [
  "OANC"
 ],
 "robust_nli/PI_CD": [
  "CC BY-SA 4.0",
  "OANC"
 ],
 "robust_nli/PI_SP": [
  "CC BY-SA 4.0",
  "OANC"
 ],
 "robust_nli/ST_LM": [
  "OANC"
 ],
 "robust_nli/ST_NE": [
  "OANC"
 ],
 "robust_nli/ST_SE": [
  "OANC"
 ],
 "robust_nli/ST_WO": [
  "OANC"
 ],
 "robust_nli_is_sd": [
  "OANC"
 ],
 "robust_nli_li_ts": [
  "OANC"
 ],
 "ruletaker": [
  "Apache License 2.0"
 ],
 "rumoureval_2019/RumourEval2019": [
  "Custom"
 ],
 "scinli": [
  "CC BY-SA 4.0"
 ],
 "scruples": [
  "Custom"
 ],
 "sem_eval_2010_task_8": [
  "CC0 1.0"
 ],
 "silicone/dyda_da": [
  "CC BY-NC-SA 4.0"
 ],
 "silicone/dyda_e": [
  "CC BY-NC-SA 4.0",
  "CC BY-SA 4.0"
 ],
 "silicone/iemocap": [
  "Custom",
  "Request Form"
 ],
 "silicone/maptask": [
  "CC BY 4.0"
 ],
 "silicone/meld_e": [
  "CC BY-NC-SA 4.0"
 ],
 "silicone/meld_s": [
  "CC BY-NC-SA 4.0"
 ],
 "silicone/oasis": [
  "CC BY-NC-SA 4.0"
 ],
 "silicone/sem": [
  "CC BY-NC-SA 4.0"
 ],
 "sms_spam": [
  "CC BY 4.0"
 ],
 "snips_built_in_intents": [
  "CC0 1.0"
 ],
 "social_i_qa": [
  "CC BY 4.0"
 ],
 "starcon": [
  "CC0 1.0"
 ],
 "webgpt_comparisons": [
  "OpenAI"
 ],
 "wouldyourather": [
  "CC0 1.0"
 ]
}

REPO_LICENSES = {
 "0n1xus/codexglue": [
  "C-UDA"
 ],
 "12ml/e-care": [
  "BSD 2-Clause License"
 ],
 "acronym_identification": [
  "CC BY-NC-SA 4.0"
 ],
 "adapting/abstract-keyphrases": [
  "MIT License"
 ],
 "adv_glue": [
  "CC BY-SA 4.0"
 ],
 "adversarial_qa": [
  "CC BY-SA 3.0",
  "MIT License"
 ],
 "aeslc": [
  "CC BY-NC-SA 4.0"
 ],
 "ag_news": [
  "Custom"
 ],
 "ai2_arc": [
  "CC BY-SA 4.0"
 ],
 "ai2lumos/lumos_unified_ground_iterative": [
  "Apache License 2.0",
  "CC BY 4.0",
  "CC BY-NC 4.0",
  "MIT License",
  "OpenAI"
 ],
 "ai2lumos/lumos_unified_plan_iterative": [
  "Apache License 2.0",
  "CC BY 4.0",
  "CC BY-NC 4.0",
  "MIT License",
  "OpenAI"
 ],
 "ai4bharat/indic-instruct-data-v0.1": [
  "Apache License 2.0",
  "CC BY 4.0",
  "CC BY-SA 3.0",
  "CC0 1.0",
  "Custom",
  "MIT License",
  "OpenAI",
  "Various"
 ],
 "ai4privacy/pii-masking-200k": [
  "Non Commercial"
 ],
 "akoksal/longform": [
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "OpenAI"
 ],
 "allenai/cochrane_dense_mean": [
  "Apache License 2.0",
  "CC BY-NC 4.0"
 ],
 "allenai/cochrane_sparse_max": [
  "Apache License 2.0"
 ],
 "allenai/cochrane_sparse_mean": [
  "Apache License 2.0",
  "CC BY-NC 4.0"
 ],
 "allenai/lila": [
  "CC BY 4.0"
 ],
 "allenai/ms2_dense_max": [
  "Apache License 2.0",
  "CC BY-NC 4.0"
 ],
 "allenai/ms2_sparse_max": [
  "Apache License 2.0",
  "CC BY-NC 4.0"
 ],
 "allenai/ms2_sparse_mean": [
  "Apache License 2.0",
  "CC BY-NC 4.0"
 ],
 "allenai/qasper": [
  "CC BY 4.0"
 ],
 "allenai/soda": [
  "Apache License 2.0",
  "CC BY 4.0",
  "OpenAI"
 ],
 "allenai/wildchat": [
  "AI2 ImpACT License - Low Risk",
  "OpenAI"
 ],
 "amazon_polarity": [
  "Apache License 2.0"
 ],
 "amazon_reviews_multi": [
  "Custom"
 ],
 "amazon_us_reviews": [
  "Custom"
 ],
 "amydeng2000/creak": [
  "CC BY-SA 4.0"
 ],
 "anli": [
  "CC BY-NC 4.0"
 ],
 "anon8231489123/sharegpt_vicuna_unfiltered": [
  "OpenAI"
 ],
 "anthropic/hh-rlhf": [
  "Apache License 2.0",
  "MIT License"
 ],
 "anthropic/model-written-evals": [
  "CC BY 4.0"
 ],
 "aqua_rat": [
  "Apache License 2.0"
 ],
 "arbml/cidar": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "argilla/news-summary": [
  "CC BY-NC-SA 4.0"
 ],
 "argilla/ultrafeedback-binarized-preferences": [
  "Apache License 2.0",
  "CC BY-NC 4.0",
  "CC BY-NC-SA 4.0",
  "Llama 2",
  "MIT License",
  "OpenAI",
  "Various"
 ],
 "arize-ai/beer_reviews_label_drift_neg": [
  "MIT License"
 ],
 "arize-ai/beer_reviews_label_drift_neutral": [
  "CC BY-NC-SA 4.0",
  "MIT License"
 ],
 "arize-ai/ecommerce_reviews_with_language_drift": [
  "MIT License"
 ],
 "ascent_kb": [
  "Apache License 2.0"
 ],
 "asset": [
  "CC BY-NC 4.0"
 ],
 "atomic": [
  "CC BY 4.0"
 ],
 "axiong/pmc_llama_instructions": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "baai/coig": [
  "Apache License 2.0",
  "CC BY-SA 4.0",
  "Various"
 ],
 "banking77": [
  "CC BY 4.0"
 ],
 "bazyl/gtsrb": [
  "GNU General Public License v3.0"
 ],
 "beki/privy": [
  "MIT License"
 ],
 "berkeley-nest/nectar": [
  "CC BY-NC 4.0",
  "Llama 2",
  "MIT License",
  "OpenAI",
  "Various"
 ],
 "bianet": [
  "CC BY-SA 4.0"
 ],
 "big_patent": [
  "CC BY-SA 4.0"
 ],
 "bigbio/an_em": [
  "CC BY-SA 3.0"
 ],
 "bigbio/chia": [
  "CC BY 4.0"
 ],
 "bigbio/ehr_rel": [
  "Apache License 2.0"
 ],
 "bigbio/gad": [
  "CC BY 4.0"
 ],
 "bigbio/mayosrs": [
  "CC0 1.0"
 ],
 "bigbio/minimayosrs": [
  "CC0 1.0"
 ],
 "bigbio/sciq": [
  "CC BY-NC 3.0"
 ],
 "bigbio/scitail": [
  "Apache License 2.0"
 ],
 "bigbio/umnsrs": [
  "CC0 1.0"
 ],
 "bigcode/commitpackft": [
  "Apache License 2.0",
  "Artistic License 2.0",
  "BSD 2-Clause License",
  "BSD 3-Clause License",
  "CC0 1.0",
  "EPL 1.0",
  "GNU General Public License v3.0",
  "ISC License",
  "LGPL 2.1",
  "MIT License",
  "MPL 2.0",
  "No License"
 ],
 "bigcode/oasst-octopack": [
  "CC BY 4.0"
 ],
 "bigcode/rosetta-code": [
  "CC BY-SA 4.0"
 ],
 "biglam/atypical_animacy": [
  "CC0 1.0"
 ],
 "bigscience/p3": [
  "Academic Free License v3.0",
  "Academic Research Purposes Only",
  "Apache License 2.0",
  "BSD 2-Clause License",
  "CC BY 4.0",
  "CC BY-NC 3.0",
  "CC BY-NC 4.0",
  "CC BY-NC-ND 4.0",
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "Custom",
  "MIT License",
  "Microsoft Data Licensing Agreement",
  "Non Commercial",
  "OANC",
  "Open Access"
 ],
 "billsum": [
  "CC0 1.0",
  "Custom"
 ],
 "biosses": [
  "GNU General Public License v3.0"
 ],
 "blimp": [
  "CC BY 4.0"
 ],
 "blog_authorship_corpus": [
  "Custom"
 ],
 "boolq": [
  "CC BY-SA 3.0"
 ],
 "bsc-temu/sqac": [
  "CC BY 2.5",
  "CC BY 4.0",
  "CC BY-SA 3.0"
 ],
 "bsc-temu/tecla": [
  "CC BY-NC-ND 4.0"
 ],
 "bsc-temu/viquiquad": [
  "CC BY-SA 3.0"
 ],
 "bsc/ancora-ca-ner": [
  "CC BY 4.0"
 ],
 "camel-ai/ai_society_translated": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "camel-ai/biology": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "camel-ai/chemistry": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "camel-ai/code": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "camel-ai/math": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "camel-ai/physics": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "casey-martin/medinstruct": [
  "OpenAI"
 ],
 "castorini/odqa-wiki-corpora": [
  "CC BY-SA 3.0"
 ],
 "catalonia_independence": [
  "CC BY-NC-SA 4.0"
 ],
 "cdt": [
  "Apache License 2.0"
 ],
 "cgarciae/cartoonset": [
  "CC BY 4.0"
 ],
 "chenghao/cuad_qa": [
  "CC BY 4.0"
 ],
 "circa": [
  "CC BY-SA 4.0"
 ],
 "civil_comments": [
  "CC0 1.0"
 ],
 "classla/copa_hr": [
  "BSD 2-Clause License"
 ],
 "clinc_oos": [
  "CC BY-SA 3.0"
 ],
 "clue": [
  "Apache License 2.0",
  "CC BY-SA 4.0",
  "Custom"
 ],
 "clusterlabai/instar-500k": [
  "Apache 2.0",
  "CC BY 4.0",
  "CC BY-NC-SA 4.0",
  "CC BY-SA 4.0",
  "MIT License"
 ],
 "cmalaviya/expertqa": [
  "MIT License",
  "OpenAI"
 ],
 "cmu-lti/cobracorpus": [
  "BigScience OpenRAIL-M",
  "OpenAI"
 ],
 "cnn_dailymail": [
  "MIT License"
 ],
 "coached_conv_pref": [
  "CC BY 4.0"
 ],
 "code_x_glue_cc_clone_detection_big_clone_bench": [
  "C-UDA"
 ],
 "code_x_glue_cc_defect_detection": [
  "CC0 1.0"
 ],
 "codedotai/code_clippy_github": [
  "LGPL 3.0"
 ],
 "codeparrot/apps": [
  "CC BY-SA 3.0"
 ],
 "codeparrot/codecomplex": [
  "CC BY 4.0"
 ],
 "codeparrot/github-code-clean": [
  "Apache License 2.0",
  "Custom"
 ],
 "codeparrot/github-jupyter-text-code-pairs": [
  "Various"
 ],
 "codeparrot/self-instruct-starcoder": [
  "BigScience OpenRAIL-M"
 ],
 "codeparrot/xlcost": [
  "CC BY-SA 4.0"
 ],
 "codeparrot/xlcost-text-to-code": [
  "CC BY-SA 4.0"
 ],
 "cohereforai/aya_dataset": [
  "Apache License 2.0"
 ],
 "collectivecognition/chats-data-2023-10-16": [
  "MIT License",
  "OpenAI"
 ],
 "common_gen": [
  "MIT License"
 ],
 "commonsense_qa": [
  "CC BY-SA 4.0",
  "MIT License"
 ],
 "coniferlm/conifer": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "conll2003": [
  "Academic Research Purposes Only",
  "Request Form"
 ],
 "conv_questions": [
  "CC BY 4.0",
  "MIT License"
 ],
 "coqa": [
  "Custom"
 ],
 "corypaik/coda": [
  "Apache License 2.0"
 ],
 "corypaik/prost": [
  "Apache License 2.0"
 ],
 "cos_e": [
  "BSD 3-Clause License"
 ],
 "cosmos_qa": [
  "CC BY 4.0"
 ],
 "covid_qa_castorini": [
  "Apache License 2.0"
 ],
 "crd3": [
  "CC BY-SA 4.0"
 ],
 "crows_pairs": [
  "CC BY-SA 4.0"
 ],
 "ctu-aic/csfever": [
  "CC BY-SA 3.0"
 ],
 "cuad": [
  "Apache License 2.0",
  "CC BY 4.0"
 ],
 "daily_dialog": [
  "CC BY-NC-SA 4.0"
 ],
 "dair-ai/emotion": [
  "Custom"
 ],
 "dart": [
  "Apache License 2.0",
  "MIT License"
 ],
 "databricks/databricks-dolly-15k": [
  "CC BY-SA 3.0"
 ],
 "datacommons_factcheck": [
  "CC BY-NC 4.0"
 ],
 "dbarbedillo/sms_spam_multilingual_collection_dataset": [
  "MIT License"
 ],
 "dbpedia_14": [
  "CC BY-SA 3.0",
  "GNU General Public License v3.0"
 ],
 "deal_or_no_dialog": [
  "CC BY-NC 4.0"
 ],
 "deepmind/code_contests": [
  "CC BY 4.0"
 ],
 "demelin/moral_stories": [
  "MIT License"
 ],
 "derek-thomas/scienceqa": [
  "CC BY-NC-SA 4.0"
 ],
 "derek-thomas/squad-v1.1-t5-question-generation": [
  "CC BY 4.0"
 ],
 "dfki-slt/few-nerd": [
  "CC BY-SA 4.0"
 ],
 "dfki-slt/wikitext_linked": [
  "CC BY-SA 4.0"
 ],
 "dibt/10k_prompts_ranked": [
  "OpenAI"
 ],
 "din0s/msmarco-nlgen": [
  "MIT License"
 ],
 "discofuse": [
  "CC BY-SA 3.0"
 ],
 "disfl_qa": [
  "CC BY 4.0"
 ],
 "djaym7/wiki_dialog": [
  "CC BY-SA 4.0"
 ],
 "doqa": [
  "CC BY-SA 4.0"
 ],
 "dream": [
  "Academic Research Purposes Only",
  "Custom"
 ],
 "drop": [
  "CC BY 4.0"
 ],
 "drt/kqa_pro": [
  "CC BY-SA 4.0"
 ],
 "duorc": [
  "MIT License",
  "Non Commercial"
 ],
 "duwuonline/uit-vsmec": [
  "MIT License"
 ],
 "dynabench/dynasent": [
  "CC BY 4.0"
 ],
 "dynabench/qa": [
  "CC BY-SA 4.0"
 ],
 "e2e_nlg": [
  "CC BY-SA 4.0"
 ],
 "e2e_nlg_cleaned": [
  "CC BY-SA 4.0"
 ],
 "ekinakyurek/ftrace": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0"
 ],
 "embedding-data/sentence-compression": [
  "Custom"
 ],
 "embo/blurb": [
  "Apache License 2.0",
  "Custom"
 ],
 "emozilla/booksum-summary-analysis_gptneox-8192": [
  "Academic Research Purposes Only"
 ],
 "empathetic_dialogues": [
  "CC BY-NC 4.0"
 ],
 "esnli": [
  "CC BY-SA 4.0"
 ],
 "eth_py150_open": [
  "Apache License 2.0"
 ],
 "eu_regulatory_ir": [
  "CC BY-NC-SA 4.0"
 ],
 "eurlex": [
  "CC BY-SA 4.0",
  "Custom"
 ],
 "europa_ecdc_tm": [
  "Custom"
 ],
 "evaluate/glue-ci": [
  "CC BY 4.0",
  "CC BY-SA 4.0",
  "CC0 1.0",
  "OANC",
  "Various"
 ],
 "exr0n/wiki-entity-similarity": [
  "MIT License"
 ],
 "fake_news_filipino": [
  "GNU General Public License v3.0"
 ],
 "fangyuan/kiwi": [
  "CC BY-SA 4.0",
  "OpenAI"
 ],
 "fever": [
  "CC BY-SA 3.0"
 ],
 "fhamborg/news_sentiment_newsmtsc": [
  "MIT License"
 ],
 "financial_phrasebank": [
  "CC BY-NC-SA 3.0"
 ],
 "flax-sentence-embeddings/stackexchange_math_jsonl": [
  "CC BY-SA 4.0"
 ],
 "flax-sentence-embeddings/stackexchange_title_best_voted_answer_jsonl": [
  "CC BY-SA 4.0"
 ],
 "flax-sentence-embeddings/stackexchange_titlebody_best_and_down_voted_answer_jsonl": [
  "CC BY-NC-SA 4.0",
  "CC BY-SA 4.0"
 ],
 "flax-sentence-embeddings/stackexchange_titlebody_best_voted_answer_jsonl": [
  "CC BY-NC-SA 4.0",
  "CC BY-SA 4.0"
 ],
 "flores": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0"
 ],
 "freebase_qa": [
  "CC BY 4.0"
 ],
 "gair/lima": [
  "CC BY-NC-SA 4.0"
 ],
 "gem/bisect": [
  "CC0 1.0"
 ],
 "gem/cochrane-simplification": [
  "CC BY 4.0"
 ],
 "gem/conversational_weather": [
  "CC BY-NC 4.0"
 ],
 "gem/dart": [
  "MIT License"
 ],
 "gem/schema_guided_dialog": [
  "CC BY-SA 4.0"
 ],
 "gem/viggo": [
  "CC BY-SA 4.0"
 ],
 "gem/web_nlg": [
  "CC BY-NC-SA 4.0"
 ],
 "gem/wiki_cat_sum": [
  "CC BY-SA 3.0"
 ],
 "gem/wiki_lingua": [
  "CC BY-NC-SA 3.0"
 ],
 "gem/xlsum": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0"
 ],
 "gigaword": [
  "Custom",
  "MIT License"
 ],
 "gimmaru/super_glue-copa": [
  "BSD 2-Clause License"
 ],
 "glaiveai/glaive-code-assistant": [
  "Apache License 2.0"
 ],
 "glaiveai/glaive-code-assistant-v2": [
  "Apache License 2.0"
 ],
 "glaiveai/glaive-code-assistant-v3": [
  "Apache License 2.0"
 ],
 "glucose": [
  "CC BY-NC 4.0"
 ],
 "glue": [
  "CC BY 3.0",
  "CC BY 4.0",
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "Custom",
  "OANC"
 ],
 "gokuls/glue_augmented_mnli": [
  "Apache License 2.0"
 ],
 "gokuls/glue_augmented_qqp": [
  "Apache License 2.0"
 ],
 "gokuls/glue_augmented_rte": [
  "Apache License 2.0",
  "Various"
 ],
 "gokuls/glue_augmented_sst2": [
  "Apache License 2.0",
  "Various"
 ],
 "gokuls/glue_augmented_stsb": [
  "Apache License 2.0",
  "Various"
 ],
 "gokuls/glue_augmented_wnli": [
  "Apache License 2.0",
  "CC BY 4.0"
 ],
 "gooaq": [
  "Apache License 2.0"
 ],
 "google_wellformed_query": [
  "CC BY-SA 4.0"
 ],
 "gorilla-llm/berkeley-function-calling-leaderboard": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "grail_qa": [
  "CC BY-SA 4.0"
 ],
 "great_code": [
  "Apache License 2.0",
  "Various"
 ],
 "gretelai/synthetic-gsm8k-reflection-405b": [
  "Meta Llama3 Community License"
 ],
 "gretelai/synthetic_text_to_sql": [
  "Apache License 2.0"
 ],
 "gsarti/magpie": [
  "CC BY 4.0"
 ],
 "gsm8k": [
  "Apache License 2.0",
  "MIT License"
 ],
 "hate_speech18": [
  "CC BY-SA 3.0"
 ],
 "hellaswag": [
  "MIT License"
 ],
 "hello-simpleai/hc3": [
  "Apache License 2.0",
  "CC BY-SA 4.0",
  "Microsoft Data Licensing Agreement",
  "OpenAI"
 ],
 "hello-simpleai/hc3-chinese": [
  "CC BY 4.0",
  "CC BY-NC 4.0",
  "CC BY-SA 4.0",
  "CC0 1.0",
  "OpenAI"
 ],
 "helsinki-nlp/tatoeba_mt": [
  "CC BY-NC-SA 4.0"
 ],
 "hind_encorp": [
  "CC BY-NC-SA 3.0"
 ],
 "hippocorpus": [
  "Custom"
 ],
 "hkust-nlp/deita-10k-v0": [
  "Apache License 2.0",
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "hlgd": [
  "Apache License 2.0"
 ],
 "hltcoe/megawika": [
  "CC BY-SA 4.0"
 ],
 "hoskinson-center/proofnet": [
  "MIT License"
 ],
 "hotpot_qa": [
  "CC BY-SA 4.0"
 ],
 "hover": [
  "CC BY-SA 4.0"
 ],
 "huggingfaceh4/helpful-anthropic-raw": [
  "MIT License"
 ],
 "huggingfaceh4/helpful-self-instruct-raw": [
  "Apache License 2.0"
 ],
 "huggingfaceh4/no_robots": [
  "CC BY-NC 4.0"
 ],
 "huggingfaceh4/ultrachat_200k": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "hybrid_qa": [
  "CC BY 4.0"
 ],
 "hyperpartisan_news_detection": [
  "CC BY 4.0",
  "CC BY-SA 4.0"
 ],
 "idea-ccnl/afqmc": [
  "Apache License 2.0"
 ],
 "inquisitive_qg": [
  "Request Form"
 ],
 "inverse-scaling/neqa": [
  "CC BY 4.0"
 ],
 "inverse-scaling/quote-repetition": [
  "CC BY 4.0"
 ],
 "inverse-scaling/redefine-math": [
  "CC BY 4.0"
 ],
 "iohadrubin/smcalflow": [
  "CC BY-SA 4.0"
 ],
 "jeopardy": [
  "Custom"
 ],
 "jfleg": [
  "CC BY-NC-SA 4.0"
 ],
 "jiangjie/ekar_english": [
  "CC BY-NC-SA 4.0"
 ],
 "jonathanli/echr": [
  "CC BY-NC-SA 4.0",
  "Custom"
 ],
 "jonathanli/eurlex": [
  "CC BY-SA 4.0",
  "Custom"
 ],
 "jondurbin/airoboros-3.2": [
  "OpenAI",
  "Various"
 ],
 "jondurbin/airoboros-gpt4-1.4.1": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "jrahn/yolochess_deepblue": [
  "GNU General Public License v3.0"
 ],
 "juletxara/xstory_cloze": [
  "CC BY-SA 4.0"
 ],
 "kaist-ai/cot-collection": [
  "Non Commercial",
  "OpenAI"
 ],
 "kaist-ai/cot-collection_multilingual": [
  "Non Commercial",
  "OpenAI"
 ],
 "kaist-ai/selfee-train": [
  "MIT License",
  "OpenAI"
 ],
 "kasnerz/hitab": [
  "C-UDA"
 ],
 "kelm": [
  "CC BY-SA 2.0"
 ],
 "khalidalt/tydiqa-goldp": [
  "CC BY-SA 3.0"
 ],
 "khalidalt/tydiqa-primary": [
  "CC BY-SA 3.0"
 ],
 "knkarthick/dialogsum": [
  "Apache License 2.0",
  "MIT License"
 ],
 "laion/oig": [
  "Apache License 2.0",
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "MIT License"
 ],
 "lama": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0"
 ],
 "lambada": [
  "CC BY 4.0"
 ],
 "lara-martin/scifi_tv_shows": [
  "CC BY 4.0"
 ],
 "lasha-nlp/condaqa": [
  "Apache License 2.0"
 ],
 "launch/gov_report": [
  "CC BY 4.0"
 ],
 "launch/open_question_type": [
  "CC BY 4.0",
  "Custom"
 ],
 "launch/reddit_qg": [
  "CC BY 4.0",
  "Custom"
 ],
 "ldjnr/capybara": [
  "Apache License 2.0",
  "CC BY-NC 4.0",
  "MIT License",
  "OpenAI"
 ],
 "ldjnr/pure-dove": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "lex_glue": [
  "Custom"
 ],
 "librispeech_asr": [
  "CC BY 4.0"
 ],
 "limit": [
  "CC BY-SA 4.0"
 ],
 "lj_speech": [
  "Custom"
 ],
 "llukas22/nlquad": [
  "CC BY-NC 3.0"
 ],
 "lmqg/qag_tweetqa": [
  "CC BY-SA 4.0"
 ],
 "lmqg/qg_squad": [
  "CC BY-SA 4.0",
  "MIT License"
 ],
 "lmqg/qg_squadshifts": [
  "CC BY 4.0"
 ],
 "lmqg/qg_subjqa": [
  "CC BY 4.0",
  "MIT License"
 ],
 "lmqg/qg_tweetqa": [
  "CC BY-SA 4.0"
 ],
 "lmsys/chatbot_arena_conversations": [
  "CC BY 4.0",
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "lmsys/lmsys-chat-1m": [
  "Anthropic",
  "LMSYS-Chat-1M Dataset License",
  "Llama 2",
  "OpenAI"
 ],
 "lmsys/toxic-chat": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "m-a-p/coig-cqia": [
  "Apache License 2.0",
  "Various"
 ],
 "magpie-align/magpie-pro-300k-filtered": [
  "Meta Llama3 Community License"
 ],
 "mariosasko/glue": [
  "CC BY 4.0",
  "CC BY-SA 4.0",
  "CC0 1.0",
  "OANC",
  "Various"
 ],
 "math_dataset": [
  "Apache License 2.0"
 ],
 "math_qa": [
  "Apache License 2.0"
 ],
 "mbpp": [
  "CC BY 4.0"
 ],
 "mbzuai/bactrian-x": [
  "CC BY-NC 4.0",
  "CC BY-SA 3.0",
  "OpenAI"
 ],
 "mcgill-nlp/topiocqa": [
  "CC BY-NC-SA 4.0"
 ],
 "md_gender_bias": [
  "MIT License"
 ],
 "med_hop": [
  "CC BY-SA 3.0"
 ],
 "medalpaca/medical_meadow_cord19": [
  "Various"
 ],
 "medalpaca/medical_meadow_medical_flashcards": [
  "Non Commercial",
  "OpenAI"
 ],
 "medalpaca/medical_meadow_mediqa": [
  "CC0 1.0"
 ],
 "medalpaca/medical_meadow_wikidoc": [
  "OpenAI"
 ],
 "medalpaca/medical_meadow_wikidoc_patient_information": [
  "OpenAI"
 ],
 "mediabiasgroup/mbib-base": [
  "CC BY-SA 4.0"
 ],
 "menyo20k_mt": [
  "Request Form"
 ],
 "merve/poetry": [
  "Apache License 2.0"
 ],
 "meta-math/metamathqa": [
  "MIT License",
  "OpenAI"
 ],
 "metaeval/babi_nli": [
  "BSD 3-Clause License"
 ],
 "metaeval/blimp_classification": [
  "Apache License 2.0"
 ],
 "metaeval/defeasible-nli": [
  "MIT License"
 ],
 "metaeval/folio": [
  "CC BY-SA 4.0"
 ],
 "metaeval/help-nli": [
  "CC BY-SA 4.0"
 ],
 "metaeval/implicit-hate-stg1": [
  "Request Form"
 ],
 "metaeval/imppres": [
  "CC BY-NC 4.0"
 ],
 "metaeval/logiqa-2.0-nli": [
  "CC BY-NC-SA 4.0"
 ],
 "metaeval/race-c": [
  "Non Commercial"
 ],
 "metaeval/recast": [
  "CC BY-SA 4.0"
 ],
 "metaeval/scinli": [
  "CC BY-SA 4.0"
 ],
 "metaeval/scruples": [
  "Custom"
 ],
 "metaeval/strategy-qa": [
  "CC BY-SA 3.0"
 ],
 "metaeval/wouldyourather": [
  "CC0 1.0"
 ],
 "micpie/unpredictable_5k": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_baseball-fantasysports-yahoo-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cappex-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster-noise": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster00": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster02": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster03": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster04": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster05": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster06": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster07": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster08": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster09": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster10": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster12": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster14": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster15": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster16": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster17": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster18": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster19": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster20": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster21": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster22": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster23": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster24": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster25": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster27": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cluster28": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_cram-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_dividend-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_en-wikipedia-org": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_ensembl-org": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_full": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_gamefaqs-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_mgoblog-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_phonearena-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_rated-low": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_rated-medium": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_sittercity-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_sporcle-com": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_unique": [
  "Apache License 2.0"
 ],
 "micpie/unpredictable_wkdu-org": [
  "Apache License 2.0"
 ],
 "microsoft/orca-math-word-problems-200k": [
  "Apache License 2.0",
  "CC BY 4.0",
  "CC BY-NC 4.0",
  "MIT License",
  "ODC BY 1.0",
  "OpenAI"
 ],
 "mkqa": [
  "Apache License 2.0"
 ],
 "mlqa": [
  "CC BY-SA 3.0"
 ],
 "mnemlaghi/widdd": [
  "Apache License 2.0"
 ],
 "mocha": [
  "CC BY-SA 4.0"
 ],
 "mrm8488/unnatural-instructions": [
  "MIT License",
  "OpenAI"
 ],
 "mrm8488/unnatural-instructions-full": [
  "Apache License 2.0",
  "MIT License",
  "OpenAI"
 ],
 "ms_marco": [
  "Custom"
 ],
 "msr_sqa": [
  "Custom"
 ],
 "msr_text_compression": [
  "Custom"
 ],
 "muennighoff/flores200": [
  "CC BY-SA 4.0"
 ],
 "muennighoff/mbpp": [
  "CC BY 4.0"
 ],
 "muennighoff/multi_eurlex": [
  "CC BY 4.0"
 ],
 "mulin/sg-holiday": [
  "MIT License"
 ],
 "multi_news": [
  "Apache License 2.0",
  "Custom"
 ],
 "multi_nli": [
  "Custom"
 ],
 "multi_nli_mismatch": [
  "CC BY 3.0",
  "CC BY-SA 3.0",
  "MIT License"
 ],
 "mwong/climate-claim-related": [
  "CC BY-SA 3.0",
  "GNU General Public License v3.0"
 ],
 "mwong/climate-evidence-related": [
  "CC BY-SA 3.0",
  "GNU General Public License v3.0"
 ],
 "mwong/fever-evidence-related": [
  "CC BY-SA 4.0"
 ],
 "mwritescode/slither-audited-smart-contracts": [
  "MIT License"
 ],
 "mwsc": [
  "CC BY 4.0"
 ],
 "narrativeqa": [
  "Apache License 2.0"
 ],
 "natural_questions": [
  "Apache License 2.0",
  "CC BY-SA 3.0"
 ],
 "neulab/docprompting-conala": [
  "MIT License"
 ],
 "neural_code_search": [
  "CC BY-NC 4.0"
 ],
 "newspop": [
  "CC BY 4.0"
 ],
 "niceblueman/icons_dataset": [
  "Apache License 2.0"
 ],
 "nlpie/llama2-medtuned-instructions": [
  "CC BY-NC 4.0"
 ],
 "nlpinas/emotes-3k": [
  "Apache License 2.0"
 ],
 "nlu_evaluation_data": [
  "CC BY-SA 4.0"
 ],
 "numer_sense": [
  "CC BY-SA 4.0",
  "MIT License"
 ],
 "nuprl/multipl-e-synthetic-solutions": [
  "BigScience OpenRAIL-M"
 ],
 "nvidia/helpsteer": [
  "CC BY 4.0"
 ],
 "nvidia/openmathinstruct-1": [
  "Apache License 2.0",
  "Custom",
  "MIT License"
 ],
 "offenseval_dravidian": [
  "CC BY 4.0"
 ],
 "ohsumed": [
  "Custom"
 ],
 "ollie": [
  "Custom"
 ],
 "onestop_qa": [
  "CC BY-SA 4.0"
 ],
 "open-orca/openorca": [
  "MIT License",
  "OpenAI",
  "Various"
 ],
 "openai/summarize_from_feedback": [
  "Apache License 2.0",
  "CC BY 4.0",
  "OpenAI"
 ],
 "openai/webgpt_comparisons": [
  "Apache License 2.0",
  "CC BY-SA 4.0",
  "OpenAI"
 ],
 "openassistant/oasst1": [
  "CC BY 4.0"
 ],
 "openassistant/oasst2": [
  "Apache License 2.0"
 ],
 "openbookqa": [
  "Apache License 2.0"
 ],
 "opinosis": [
  "Apache License 2.0"
 ],
 "opus_paracrawl": [
  "CC0 1.0"
 ],
 "opus_tedtalks": [
  "CC BY-NC-SA 3.0"
 ],
 "papluca/language-identification": [
  "CC BY-NC 4.0",
  "CC BY-SA 4.0",
  "Custom"
 ],
 "para_crawl": [
  "CC0 1.0"
 ],
 "para_pat": [
  "GNU General Public License v3.0"
 ],
 "pasinit/xlwic": [
  "CC BY-NC 4.0"
 ],
 "paws": [
  "Custom"
 ],
 "paws-x": [
  "CC BY-SA 3.0",
  "Custom"
 ],
 "pec": [
  "GNU General Public License v3.0"
 ],
 "pib": [
  "CC BY-SA 4.0"
 ],
 "pic/phrase_sense_disambiguation": [
  "CC BY-NC 4.0",
  "MIT License"
 ],
 "pic/phrase_similarity": [
  "CC BY-NC 4.0"
 ],
 "pietrolesci/add_one_rte": [
  "Non Commercial"
 ],
 "pietrolesci/breaking_nli": [
  "CC BY-SA 4.0"
 ],
 "pietrolesci/dnc": [
  "Various"
 ],
 "pietrolesci/gen_debiased_nli": [
  "CC BY-SA 4.0",
  "OANC"
 ],
 "pietrolesci/glue_diagnostics": [
  "CC BY-SA 4.0"
 ],
 "pietrolesci/robust_nli": [
  "CC BY-SA 4.0",
  "MIT License",
  "OANC"
 ],
 "pietrolesci/robust_nli_is_sd": [
  "OANC"
 ],
 "pietrolesci/robust_nli_li_ts": [
  "OANC"
 ],
 "pile-of-law/eoir_privacy": [
  "CC BY-NC-SA 4.0"
 ],
 "pile-of-law/pile-of-law": [
  "CC BY-SA 4.0"
 ],
 "piqa": [
  "Academic Free License v3.0"
 ],
 "pkavumba/balanced-copa": [
  "BSD 2-Clause License"
 ],
 "pnlphub/farstail": [
  "Apache License 2.0"
 ],
 "poem_sentiment": [
  "CC BY 4.0"
 ],
 "polinaeterna/xsum": [
  "MIT License"
 ],
 "polyai/banking77": [
  "CC BY 4.0"
 ],
 "prometheus-eval/feedback-collection": [
  "MIT License",
  "OpenAI"
 ],
 "prometheus-eval/preference-collection": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "proto_qa": [
  "CC BY 4.0"
 ],
 "pubmed_qa": [
  "MIT License"
 ],
 "pygmalionai/pippa": [
  "Apache License 2.0"
 ],
 "qasc": [
  "CC BY 4.0"
 ],
 "qed": [
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "GNU General Public License v3.0"
 ],
 "qed_amara": [
  "Custom"
 ],
 "quac": [
  "CC BY-SA 4.0"
 ],
 "quail": [
  "CC BY-NC-SA 4.0"
 ],
 "quarel": [
  "CC BY 4.0"
 ],
 "quartz": [
  "CC BY 4.0"
 ],
 "quickdraw": [
  "CC BY 4.0"
 ],
 "quoref": [
  "CC BY 4.0"
 ],
 "race": [
  "Custom"
 ],
 "rajistics/auditor_review": [
  "CC BY-NC-SA 3.0"
 ],
 "recipe_nlg": [
  "Custom"
 ],
 "relbert/lexical_relation_classification": [
  "CC BY-NC 4.0"
 ],
 "riddle_sense": [
  "MIT License",
  "Request Form"
 ],
 "ro_sts_parallel": [
  "CC BY-SA 4.0"
 ],
 "roneneldan/tinystories": [
  "CDLA Sharing 1.0",
  "OpenAI"
 ],
 "ropes": [
  "CC BY 4.0"
 ],
 "sagnikrayc/snli-bt": [
  "Academic Free License v3.0",
  "CC BY 4.0",
  "Custom"
 ],
 "sagnikrayc/snli-cf-kaushik": [
  "Apache License 2.0",
  "CC BY 4.0"
 ],
 "sahil2801/codealpaca-20k": [
  "OpenAI"
 ],
 "samsum": [
  "Apache License 2.0",
  "CC BY-NC-ND 4.0"
 ],
 "sandipan1994/eqasc_data": [
  "CC BY 4.0"
 ],
 "scan": [
  "BSD 3-Clause License"
 ],
 "schema_guided_dstc8": [
  "CC BY-SA 4.0"
 ],
 "scifact": [
  "CC BY-NC 2.0"
 ],
 "sciq": [
  "CC BY-NC 3.0"
 ],
 "scitail": [
  "Apache License 2.0"
 ],
 "seallms/sea-bench": [
  "Apache License 2.0"
 ],
 "sede": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "sedthh/ubuntu_dialogue_qa": [
  "MIT License"
 ],
 "selqa": [
  "Apache License 2.0"
 ],
 "sem_eval_2010_task_8": [
  "CC0 1.0"
 ],
 "sem_eval_2018_task_1": [
  "Custom"
 ],
 "sentiment140": [
  "Custom"
 ],
 "setfit/mnli": [
  "OANC"
 ],
 "setfit/qnli": [
  "CC BY-SA 4.0"
 ],
 "setfit/rte": [
  "Custom"
 ],
 "setfit/wnli": [
  "CC BY 4.0"
 ],
 "severo/embellishments": [
  "CC0 1.0"
 ],
 "severo/glue": [
  "CC BY 4.0",
  "CC BY-SA 4.0",
  "CC0 1.0",
  "OANC"
 ],
 "sharc": [
  "CC BY-SA 3.0"
 ],
 "sick": [
  "CC BY 3.0",
  "CC BY-NC-SA 3.0"
 ],
 "sileod/mindgames": [
  "Apache License 2.0"
 ],
 "sileod/probability_words_nli": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "silicone": [
  "CC BY 4.0",
  "CC BY-NC-SA 4.0",
  "CC BY-SA 4.0",
  "Custom",
  "Request Form"
 ],
 "skunkworksai/reasoning-0.01": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "sms_spam": [
  "CC BY 4.0"
 ],
 "snips_built_in_intents": [
  "CC0 1.0"
 ],
 "snli": [
  "CC BY 4.0",
  "CC BY-SA 4.0",
  "Custom"
 ],
 "social_i_qa": [
  "CC BY 4.0"
 ],
 "socialgrep/one-year-of-r-india": [
  "CC BY 4.0"
 ],
 "socialgrep/one-year-of-tsla-on-reddit": [
  "CC BY 4.0"
 ],
 "socialgrep/reddit-crypto-aug-2021": [
  "CC BY 4.0"
 ],
 "socialgrep/reddit-r-bitcoin-data-for-jun-2022": [
  "CC BY 4.0"
 ],
 "socialgrep/reddit-wallstreetbets-aug-2021": [
  "CC BY 4.0"
 ],
 "socialgrep/ten-million-reddit-answers": [
  "CC BY 4.0"
 ],
 "socialgrep/the-antiwork-subreddit-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/the-reddit-climate-change-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/the-reddit-dataset-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/the-reddit-irl-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/the-reddit-nft-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/the-reddit-place-dataset": [
  "CC BY 4.0"
 ],
 "socialgrep/top-american-universities-on-reddit": [
  "CC BY 4.0"
 ],
 "speedofmagic/ontonotes_english": [
  "No License"
 ],
 "spider": [
  "CC BY-SA 4.0"
 ],
 "squad": [
  "CC BY-SA 4.0"
 ],
 "squad_v2": [
  "Apache License 2.0",
  "CC BY-SA 4.0"
 ],
 "sst2": [
  "CC0 1.0"
 ],
 "stanfordnlp/shp": [
  "Custom"
 ],
 "stingning/ultrachat": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "stjokerli/texttotext_multirc_seqio": [
  "Custom"
 ],
 "strombergnlp/broad_twitter_corpus": [
  "CC BY 4.0"
 ],
 "strombergnlp/rumoureval_2019": [
  "CC BY 4.0",
  "Custom"
 ],
 "super_glue": [
  "CC BY-SA 3.0",
  "Custom"
 ],
 "svakulenk0/qrecc": [
  "CC BY-SA 3.0"
 ],
 "swda": [
  "CC BY-NC-SA 3.0"
 ],
 "taln-ls2n/kptimes": [
  "CC BY 4.0"
 ],
 "taskmaster3": [
  "CC BY 4.0"
 ],
 "tasksource/bigbench": [
  "Apache License 2.0",
  "CC BY-SA 3.0",
  "CC BY-SA 4.0",
  "CC0 1.0",
  "Custom",
  "MIT License"
 ],
 "tasksource/conceptrules_v2": [
  "Custom"
 ],
 "tasksource/control-nli": [
  "CC BY-NC-SA 4.0"
 ],
 "tasksource/ruletaker": [
  "Apache License 2.0"
 ],
 "tasksource/sherliic": [
  "CC BY 4.0"
 ],
 "tasksource/starcon": [
  "CC0 1.0"
 ],
 "tasksource/trofi": [
  "Custom"
 ],
 "tatsu-lab/alpaca": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "tau/sled": [
  "MIT License"
 ],
 "team-pixel/rendered-wikipedia-english": [
  "GNU General Public License v3.0"
 ],
 "teknium/gpt4-llm-cleaned": [
  "CC BY-NC 4.0",
  "OpenAI"
 ],
 "teknium/gpteacher-general-instruct": [
  "MIT License",
  "OpenAI"
 ],
 "teven/code_docstring_corpus": [
  "Various"
 ],
 "thai_toxicity_tweet": [
  "CC BY-NC-SA 4.0"
 ],
 "thaweewat/alpaca-cleaned-52k-th": [
  "CC BY-NC 4.0",
  "CC BY-SA 3.0",
  "Google Cloud Translation API",
  "OpenAI"
 ],
 "thaweewat/databricks-dolly-15k-th": [
  "CC BY-SA 3.0",
  "Google Cloud Translation API"
 ],
 "thaweewat/gpteacher-20k-th": [
  "CC BY-SA 3.0",
  "Google Cloud Translation API",
  "MIT License",
  "OpenAI"
 ],
 "theblackcat102/joke_explaination": [
  "MIT License"
 ],
 "thudm/agentinstruct": [
  "CC BY 4.0",
  "MIT License",
  "OpenAI"
 ],
 "thudm/longalign-10k": [
  "Anthropic",
  "Apache License 2.0",
  "OpenAI"
 ],
 "tiagoblima/nilc-school-books": [
  "CC BY 4.0",
  "MIT License"
 ],
 "tidrael/tsl_news": [
  "Apache License 2.0"
 ],
 "tiger-lab/mathinstruct": [
  "MIT License",
  "OpenAI"
 ],
 "tigerresearch/tigerbot-kaggle-leetcodesolutions-en-2k": [
  "Apache License 2.0",
  "GNU General Public License v3.0"
 ],
 "timdettmers/openassistant-guanaco": [
  "Apache License 2.0"
 ],
 "toloka/crowdspeech": [
  "Apache License 2.0"
 ],
 "totally-not-an-llm/everythinglm-data-v3": [
  "MIT License",
  "OpenAI"
 ],
 "trec": [
  "CC0 1.0"
 ],
 "trivia_qa": [
  "Apache License 2.0"
 ],
 "troboto/names": [
  "CC BY 4.0"
 ],
 "truthful_qa": [
  "Apache License 2.0"
 ],
 "turingbench/turingbench": [
  "Apache License 2.0"
 ],
 "tweet_qa": [
  "CC BY-SA 4.0"
 ],
 "ucl-dark/ludwig": [
  "CC BY 4.0",
  "MIT License"
 ],
 "unpredictable/unpredictable_5k": [
  "Apache License 2.0"
 ],
 "unpredictable/unpredictable_full": [
  "Apache License 2.0"
 ],
 "usc-isi/wikiconvert": [
  "MIT License"
 ],
 "voidful/iirc": [
  "CC BY 4.0"
 ],
 "wangrongsheng/genmedgpt-5k-en": [
  "OpenAI"
 ],
 "web_nlg": [
  "CC BY-NC 4.0",
  "CC BY-NC-SA 4.0"
 ],
 "web_questions": [
  "CC BY 4.0"
 ],
 "webis/args_me": [
  "CC BY 4.0"
 ],
 "webis/touche23-valueeval": [
  "CC BY 4.0"
 ],
 "wenhu/theoremqa": [
  "MIT License",
  "OpenAI"
 ],
 "wiki_auto": [
  "CC BY-SA 4.0",
  "Request Form"
 ],
 "wiki_bio": [
  "CC BY-SA 3.0"
 ],
 "wiki_hop": [
  "CC BY-SA 3.0"
 ],
 "wiki_lingua": [
  "CC BY 3.0"
 ],
 "wiki_qa": [
  "Custom",
  "Microsoft Data Licensing Agreement"
 ],
 "wiki_split": [
  "CC BY-SA 4.0"
 ],
 "wikitext": [
  "CC BY-SA 3.0"
 ],
 "winograd_wsc": [
  "CC BY 4.0"
 ],
 "winograd_wsc;": [
  "CC BY 4.0"
 ],
 "winogrande": [
  "CC BY 4.0"
 ],
 "wiqa": [
  "Apache License 2.0"
 ],
 "wise-east/spolin": [
  "CC BY-NC 4.0"
 ],
 "wisesight_sentiment": [
  "CC0 1.0"
 ],
 "wizardlm/evol_instruct_70k": [
  "Academic Research Purposes Only",
  "OpenAI"
 ],
 "wizardlm/wizardlm_evol_instruct_v2_196k": [
  "Academic Research Purposes Only",
  "OpenAI"
 ],
 "wongnai_reviews": [
  "LGPL 3.0"
 ],
 "xcopa": [
  "CC BY 4.0"
 ],
 "xcsr": [
  "Request Form"
 ],
 "xnli": [
  "CC BY-NC 4.0"
 ],
 "xpitfire/cmp_facade": [
  "CC BY-SA 4.0"
 ],
 "xquad": [
  "CC BY-SA 4.0"
 ],
 "yangdong/ecqa": [
  "CDLA Sharing 1.0"
 ],
 "yawnick/para_crawl_enen": [
  "CC0 1.0"
 ],
 "yelp_review_full": [
  "Custom"
 ],
 "yizhongw/self_instruct": [
  "Apache License 2.0",
  "OpenAI"
 ],
 "zest": [
  "CC BY 4.0"
 ],
 "zpn/bace_classification": [
  "MIT License"
 ],
 "zpn/bbbp": [
  "MIT License"
 ],
 "zpn/clintox": [
  "MIT License"
 ],
 "zpn/pcba_686978": [
  "MIT License"
 ],
 "zpn/pubchem_selfies": [
  "Non Commercial"
 ],
 "zpn/zinc20": [
  "MIT License"
 ]
}

LICENSE_USE = {
 "AI2 ImpACT License - Low Risk": "All",
 "Academic Free License v3.0": "All",
 "Academic Research Purposes Only": "Acad",
 "Anthropic": "NC",
 "Apache 2.0": "All",
 "Apache License 2.0": "All",
 "Artistic License 2.0": "All",
 "BSD 2-Clause License": "All",
 "BSD 3-Clause License": "All",
 "BigScience OpenRAIL-M": "All",
 "C-UDA": "All",
 "CC BY 2.5": "All",
 "CC BY 3.0": "All",
 "CC BY 4.0": "All",
 "CC BY-NC 2.0": "NC",
 "CC BY-NC 3.0": "NC",
 "CC BY-NC 4.0": "NC",
 "CC BY-NC-ND 4.0": "NC",
 "CC BY-NC-SA 3.0": "NC",
 "CC BY-NC-SA 4.0": "NC",
 "CC BY-SA 2.0": "All",
 "CC BY-SA 3.0": "All",
 "CC BY-SA 4.0": "All",
 "CC0 1.0": "All",
 "CDLA Sharing 1.0": "All",
 "EPL 1.0": "All",
 "GNU General Public License v3.0": "All",
 "Google Cloud Translation API": "NC",
 "ISC License": "All",
 "LGPL 2.1": "All",
 "LGPL 3.0": "All",
 "LMSYS-Chat-1M Dataset License": "All",
 "Llama 2": "All",
 "MIT License": "All",
 "MPL 2.0": "All",
 "Meta Llama3 Community License": "All",
 "Microsoft Data Licensing Agreement": "Acad",
 "No License": "All",
 "Non Commercial": "NC",
 "OANC": "All",
 "ODC BY 1.0": "All",
 "Open Access": "All",
 "OpenAI": "NC",
 "Request Form": "Acad",
 "Various": "Acad"
}
