"""Snapshot the license metadata behind ``tasksource.licenses``.

Writes two checked-in modules; nothing is fetched at import:

- ``metadata/card_licenses.py``: the ``license`` of the Hub card of every
  dataset a task loads or originates from (``tasksource.hub_datasets``).
- ``metadata/dpi_licenses.py``: the licenses the Data Provenance Initiative
  records for each tasksource task id (its Tasksource collections) and each Hub
  dataset (every collection), with DPI's use class per license. Entries DPI
  marks only "Unspecified" are left out.
"""

import argparse
import json
import re
import subprocess
import urllib.parse
import urllib.request
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

REPO = "Data-Provenance-Initiative/Data-Provenance-Collection"
METADATA = Path(__file__).resolve().parents[1] / "src" / "tasksource" / "metadata"
HF_URL = re.compile(r"huggingface\.co/datasets/([^/?#\s]+(?:/[^/?#\s]+)?)")


def gh(path):
    return json.loads(subprocess.run(["gh", "api", path], capture_output=True, text=True, check=True).stdout)


def fetch(commit, name):
    url = f"https://raw.githubusercontent.com/{REPO}/{commit}/{urllib.parse.quote(name)}"
    return json.loads(urllib.request.urlopen(url).read())


def update_cards():
    from tasksource import hub_datasets
    from tasksource.jev.procedural import REPO_ID
    from tasksource.licenses import fetch_card_licenses

    cards = fetch_card_licenses(set(hub_datasets()) | {REPO_ID})
    (METADATA / "card_licenses.py").write_text(
        '"""Hub dataset card licenses (generated by scripts/update_licenses.py).\n\n'
        'Repo -> the card\'s ``license`` list, ``unknown`` dropped; empty when the card has none."""\n\n'
        f"CARD_LICENSES = {json.dumps(cards, indent=1, sort_keys=True, ensure_ascii=False)}\n",
        encoding="utf-8",
    )
    print(f"{len(cards)} cards, {sum(bool(v) for v in cards.values())} with a license")


def update_dpi(commit):
    commit = commit or gh(f"repos/{REPO}/commits/main")["sha"]
    names = [entry["name"] for entry in gh(f"repos/{REPO}/contents/data_summaries?ref={commit}")
             if entry["name"].endswith(".json")]
    with ThreadPoolExecutor(16) as pool:
        collections = list(pool.map(lambda name: fetch(commit, f"data_summaries/{name}"), names))
    classes = fetch(commit, "constants/license_classes.json")
    tasks, repos = {}, {}
    for collection in collections:
        for entry in collection.values():
            licenses = sorted({item["License"] for item in entry.get("Licenses", [])} - {"Unspecified"})
            if not licenses:
                continue
            if entry.get("Collection", "").startswith("Tasksource"):
                for task in entry.get("Dataset Filter IDs", []):
                    tasks.setdefault(task, set()).update(licenses)
            hub = {(entry.get("Inferred Metadata") or {}).get("HF Dataset")}
            hub.update(HF_URL.findall(entry.get("Hugging Face URL") or ""))
            for repo in filter(None, hub):
                repos.setdefault(repo.lower(), set()).update(licenses)
    used = set().union(*tasks.values(), *repos.values())
    use = {name: classes[name][0] for name in sorted(used) if name in classes}
    render = lambda mapping: json.dumps({k: sorted(v) for k, v in sorted(mapping.items())}, indent=1, ensure_ascii=False)
    (METADATA / "dpi_licenses.py").write_text(
        f'"""Data Provenance Initiative license annotations (generated by scripts/update_dpi_licenses.py).\n\n'
        f"https://github.com/{REPO} at {commit}.\n"
        f"TASK_LICENSES: tasksource task id -> licenses; REPO_LICENSES: lowercase Hub dataset -> licenses;\n"
        f'LICENSE_USE: license -> DPI use class ("All": commercial, "NC", "Acad", "Unspecified").\n"""\n\n'
        f'DPI_COMMIT = "{commit}"\n\n'
        f"TASK_LICENSES = {render(tasks)}\n\n"
        f"REPO_LICENSES = {render(repos)}\n\n"
        f"LICENSE_USE = {json.dumps(use, indent=1, ensure_ascii=False)}\n",
        encoding="utf-8",
    )
    print(f"{len(tasks)} tasks, {len(repos)} repos, {len(use)} licenses at {commit}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--commit", help="DPI commit to snapshot; default is the current main.")
    parser.add_argument("--only", choices=["cards", "dpi"])
    args = parser.parse_args()
    if args.only != "cards":
        update_dpi(args.commit)
    if args.only != "dpi":
        update_cards()
