"""Turn a per-task Jev audit into sampling weights (src/tasksource/metadata/audit_weights.py).

Jev's chance-adjusted accuracy on up to 200 direct decisions per task says how
hard a task is; the kind of gold says what a failure means:

- trivial (kappa >= 0.9): little signal left, weight 0.5
- hard (kappa < 0.35) with gold right by construction (synthetic, formal logic):
  Jev's failures are signal, weight 1.5
- hard with gold that is a judgment call (ratings, preferences, crowd sentiment,
  annotator disagreement): low agreement is partly noise, weight 0.5
- everything else, and tasks repaired after the audit, keep weight 1

The adjudicator's (DeepSeek) agreement is not used: on real tasks it mostly shares
Jev's errors (it sided with Jev on 60% of disagreements, but on 12% where gold is exact).

    python scripts/update_audit_weights.py build/jev-task-audit build/jev-task-audit-fixed
"""

import argparse
import re
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
CLEAN = (r"^(tomi-nli|corr2cause|babi_nli/|puzzte|regset|SpaRTUN|spartqa|conceptrules|logiqa|help-nli|FLD|clutrr"
         r"|proofwriter|stepgame|nlgraph|lsat|LogicNLI|logical-entailment|probability_words_nli|sen-making|docred"
         r"|TuringBench)")
SUBJECTIVE = (r"(_Disagreement$|^english-grading/|^AES2|^HelpSteer|^oasst2/|^hh-rlhf/|^SHP|^webgpt|^crowdflower/"
              r"|^argument-feedback|^liar$|^google_wellformed|^pragmeval/(squinky|persuasiveness|verifiability|emobank)"
              r"|^esci$|^humicroedit|^wouldyourather|^go_emotions|^tweet_eval/(emoji|stance|hate)|^emo/"
              r"|^blog_authorship|MLMA_hate|^multilingual/offenseval|^utilitarianism|^VUAC$|^poem_sentiment"
              r"|^multilingual/x-fact|^multilingual/xglue/(wpr|qadsm)|indic_glue/.*sentiment|^subjectivity$)")


def verdict(task, kappa, repaired):
    if repaired:
        return "repaired", 1.0
    if kappa >= 0.9:
        return "trivial", 0.5
    if kappa < 0.35 and re.search(CLEAN, task):
        return "hard-clean", 1.5
    if kappa < 0.35 and re.search(SUBJECTIVE, task):
        return "hard-subjective", 0.5
    return "hard" if kappa < 0.35 else "ok", 1.0


def kappas(audit_dir):
    """Jev's accuracy above chance per task, from decisions.jsonl."""
    decisions = pd.read_json(Path(audit_dir) / "decisions.jsonl", lines=True)
    decisions["chance"] = decisions.jev_probabilities.map(lambda p: 0.5 if len(p) == 1 else 1 / len(p))
    decisions["correct"] = decisions.gold == decisions.jev
    per_task = decisions.groupby("source").agg(accuracy=("correct", "mean"), chance=("chance", "mean"))
    return (per_task.accuracy - per_task.chance) / (1 - per_task.chance)


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("audit", help="audit output directory (all tasks)")
    parser.add_argument("repaired", nargs="?", help="audit of tasks re-evaluated after repairs; these override")
    parser.add_argument("--out", type=Path, default=ROOT / "src/tasksource/metadata/audit_weights.py")
    args = parser.parse_args()
    kappa = kappas(args.audit)
    repaired = set()
    if args.repaired:
        after = kappas(args.repaired)
        repaired = set(after.index)
        kappa.update(after)
    rows = sorted((task, *verdict(task, k, task in repaired), k) for task, k in kappa.items())
    lines = [f'    "{task}": {weight},  # {name}, kappa {k:.2f}' for task, name, weight, k in rows if weight != 1]
    args.out.write_text(
        '"""Sampling weights from the per-task Jev audit (generated by scripts/update_audit_weights.py).\n\n'
        "Multiplies metadata.weights; tasks not listed weigh 1. See the script for the rules.\n"
        '"""\n\nAUDIT_WEIGHTS = {\n' + "\n".join(lines) + "\n}\n")
    counts = pd.Series([name for _, name, _, _ in rows]).value_counts().to_dict()
    print(f"{len(lines)} weighted tasks written to {args.out}: {counts}")


if __name__ == "__main__":
    main()
